// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/introduction": {
    params: {};
  };
  "/guide": {
    params: {};
  };
  "/guppy": {
    params: {};
  };
  "/goldfish": {
    params: {};
  };
  "/platy": {
    params: {};
  };
  "/betta": {
    params: {};
  };
  "/molly": {
    params: {};
  };
  "/tetra": {
    params: {};
  };
  "/zebra": {
    params: {};
  };
  "/ai": {
    params: {};
  };
  "/about": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/introduction" | "/guide" | "/guppy" | "/goldfish" | "/platy" | "/betta" | "/molly" | "/tetra" | "/zebra" | "/ai" | "/about";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/introduction.tsx": {
    id: "routes/introduction";
    page: "/introduction";
  };
  "routes/Guide.tsx": {
    id: "routes/Guide";
    page: "/guide";
  };
  "routes/guppy.tsx": {
    id: "routes/guppy";
    page: "/guppy";
  };
  "routes/goldfish.tsx": {
    id: "routes/goldfish";
    page: "/goldfish";
  };
  "routes/platy.tsx": {
    id: "routes/platy";
    page: "/platy";
  };
  "routes/betta.tsx": {
    id: "routes/betta";
    page: "/betta";
  };
  "routes/molly.tsx": {
    id: "routes/molly";
    page: "/molly";
  };
  "routes/tetra.tsx": {
    id: "routes/tetra";
    page: "/tetra";
  };
  "routes/zebra.tsx": {
    id: "routes/zebra";
    page: "/zebra";
  };
  "routes/ai.tsx": {
    id: "routes/ai";
    page: "/ai";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
};