// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/introduction": {
    params: {};
  };
  "/guide": {
    params: {};
  };
  "/guppy": {
    params: {};
  };
  "/goldfish": {
    params: {};
  };
  "/platy": {
    params: {};
  };
  "/betta": {
    params: {};
  };
  "/molly": {
    params: {};
  };
  "/tetra": {
    params: {};
  };
  "/zebra-danio": {
    params: {};
  };
  "/angelfish": {
    params: {};
  };
  "/corydoras": {
    params: {};
  };
  "/Rainbowfish": {
    params: {};
  };
  "/Gowrami": {
    params: {};
  };
  "/ai": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/swordtail": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/introduction" | "/guide" | "/guppy" | "/goldfish" | "/platy" | "/betta" | "/molly" | "/tetra" | "/zebra-danio" | "/angelfish" | "/corydoras" | "/Rainbowfish" | "/Gowrami" | "/ai" | "/about" | "/swordtail";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/introduction.tsx": {
    id: "routes/introduction";
    page: "/introduction";
  };
  "routes/Guide.tsx": {
    id: "routes/Guide";
    page: "/guide";
  };
  "routes/guppy.tsx": {
    id: "routes/guppy";
    page: "/guppy";
  };
  "routes/goldfish.tsx": {
    id: "routes/goldfish";
    page: "/goldfish";
  };
  "routes/platy.tsx": {
    id: "routes/platy";
    page: "/platy";
  };
  "routes/betta.tsx": {
    id: "routes/betta";
    page: "/betta";
  };
  "routes/molly.tsx": {
    id: "routes/molly";
    page: "/molly";
  };
  "routes/tetra.tsx": {
    id: "routes/tetra";
    page: "/tetra";
  };
  "routes/zebra.tsx": {
    id: "routes/zebra";
    page: "/zebra-danio";
  };
  "routes/angel.tsx": {
    id: "routes/angel";
    page: "/angelfish";
  };
  "routes/Corydorascatfish.tsx": {
    id: "routes/Corydorascatfish";
    page: "/corydoras";
  };
  "routes/barbs.tsx": {
    id: "routes/barbs";
    page: "/Rainbowfish";
  };
  "routes/gowrami.tsx": {
    id: "routes/gowrami";
    page: "/Gowrami";
  };
  "routes/ai.tsx": {
    id: "routes/ai";
    page: "/ai";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/swordtail.tsx": {
    id: "routes/swordtail";
    page: "/swordtail";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/introduction": typeof import("./app/routes/introduction.tsx");
  "routes/Guide": typeof import("./app/routes/Guide.tsx");
  "routes/guppy": typeof import("./app/routes/guppy.tsx");
  "routes/goldfish": typeof import("./app/routes/goldfish.tsx");
  "routes/platy": typeof import("./app/routes/platy.tsx");
  "routes/betta": typeof import("./app/routes/betta.tsx");
  "routes/molly": typeof import("./app/routes/molly.tsx");
  "routes/tetra": typeof import("./app/routes/tetra.tsx");
  "routes/zebra": typeof import("./app/routes/zebra.tsx");
  "routes/angel": typeof import("./app/routes/angel.tsx");
  "routes/Corydorascatfish": typeof import("./app/routes/Corydorascatfish.tsx");
  "routes/barbs": typeof import("./app/routes/barbs.tsx");
  "routes/gowrami": typeof import("./app/routes/gowrami.tsx");
  "routes/ai": typeof import("./app/routes/ai.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/swordtail": typeof import("./app/routes/swordtail.tsx");
};